### ISSUE TITLE
Update to stable diffusion broke script

### ISSUE THREAD

**Issue by lemonade10-code** [0xALIVEBEEF/Expanded-XY-grid#1]
A update to the Stable Diffusion file modules/process.py file removed the get_correct_sampler function.
So when Stable Diffusion is run it causes the following error:
"ImportError: cannot import name 'get_correct_sampler' from 'modules.processing' (/notebooks/stable-diffusion-webui/modules/processing.py)".

Sadly this stops the script from loading.

**Comment by 0xALIVEBEEF** [comment]
Ok. I'll have to look into fixing that.

**Comment by OracoloJanus** [comment]
Another plugin had the same problem and fixed it.
Maybe it can help you.
https://github.com/xrpgame/xyz_plot_script
https://github.com/Gerschel/xyz-plot-grid/commit/0786dc8700f0823dc0633aec7cc83d6ad5f0c2a3

**Comment by 0xALIVEBEEF** [comment]
I fixed it, but it completely broke elsewhere. 
![image](https://user-images.githubusercontent.com/80003301/202974938-d9a61c75-8e88-49ae-ab0f-d42588b7a26a.png)
Now the boxes don't even show up even though the ui method (function) code is exactly the same.

**Comment by 0xALIVEBEEF** [comment]
It is now fixed
